version: '3.8'

services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=dev  # Set the active profile to 'dev'
    networks:
      - backend_network

  db:
    image: mysql:8.0
    container_name: backend-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
